name: mxxd
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+44

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+1
  http: ^0.12.0+2
  mime: ^0.9.6+3
  sqflite: ^1.1.6+2
  flutter_tts: ^0.2.6
  path: ^1.6.2
  path_provider: any
  bloc_pattern: ^2.2.3
  rxdart: ^0.22.1+1
  archive: ^2.0.9
  progress_hud: ^1.1.0
  hex: ^0.1.2
  package_info: ^0.4.0+4
  device_info: ^0.4.0+2
  get_version: ^0.1.0
  cookie_jar: ^1.0.0
  dio: ^3.0.3
  dio_cookie_manager: ^1.0.0
  dio_http2_adapter: ^1.0.0
  percent_indicator: ^2.1.0
  charts_flutter: ^0.8.1
  crypto: ^2.0.6
  audioplayers: ^0.13.1
  large_file_copy: ^0.0.1
  flutter_mailer: ^0.4.1+1
  app_review: ^1.0.0
  webview_flutter: ^0.3.9+1
  url_launcher: ^5.0.3
  sprintf: ^4.0.2
  intl: ^0.16.0
  intl_translation: ^0.17.5
  flutter_svg:
    git:
      url: https://github.com/wershest/flutter_svg.git
      ref: "0.74"

dev_dependencies:
  mockito: ^4.0.0
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter
  test: ^1.5.1

  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/common-words
    - assets/mems.rdb
    - assets/search_history.rdb
    - assets/icons/
    - assets/images/
    - assets/fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Fjalla One
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
